export interface EnvTemplateVars {
  projectName: string;
  port: number;
  tokenSecretHex: string;
  csfleKeyHex: string;
  ssfSigningSecret: string;
  enableGoogle: boolean;
  enableGitHub: boolean;
  enableFacebook: boolean;
  enableApple: boolean;
  enableEmailMfa: boolean;
  enableSmsMfa: boolean;
  enableWhatsAppMfa: boolean;
  enableTelegramMfa: boolean;
  useDocker: boolean;
}

/**
 * Build a complete, annotated .env file from template variables.
 * Lines with auto-generated secrets are marked, empty credentials
 * are left as stubs to be filled by the user.
 */
export function buildEnvContent(vars: EnvTemplateVars): string {
  const mongoUri = vars.useDocker
    ? "mongodb://admin:password@localhost:27017/zeroauth?authSource=admin"
    : "mongodb://localhost:27017/zeroauth";

  const redisUri = vars.useDocker
    ? "redis://:redispass@localhost:6379"
    : "redis://localhost:6379";

  const googleBlock = vars.enableGoogle
    ? `OAUTH_GOOGLE_CLIENT_ID=
OAUTH_GOOGLE_CLIENT_SECRET=
OAUTH_GOOGLE_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/google/callback`
    : `# OAUTH_GOOGLE_CLIENT_ID=
# OAUTH_GOOGLE_CLIENT_SECRET=
# OAUTH_GOOGLE_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/google/callback`;

  const githubBlock = vars.enableGitHub
    ? `OAUTH_GITHUB_CLIENT_ID=
OAUTH_GITHUB_CLIENT_SECRET=
OAUTH_GITHUB_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/github/callback`
    : `# OAUTH_GITHUB_CLIENT_ID=
# OAUTH_GITHUB_CLIENT_SECRET=
# OAUTH_GITHUB_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/github/callback`;

  const facebookBlock = vars.enableFacebook
    ? `OAUTH_FACEBOOK_CLIENT_ID=
OAUTH_FACEBOOK_CLIENT_SECRET=
OAUTH_FACEBOOK_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/facebook/callback`
    : `# OAUTH_FACEBOOK_CLIENT_ID=
# OAUTH_FACEBOOK_CLIENT_SECRET=
# OAUTH_FACEBOOK_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/facebook/callback`;

  const appleBlock = vars.enableApple
    ? `OAUTH_APPLE_CLIENT_ID=
OAUTH_APPLE_CLIENT_SECRET=
OAUTH_APPLE_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/apple/callback`
    : `# OAUTH_APPLE_CLIENT_ID=
# OAUTH_APPLE_CLIENT_SECRET=
# OAUTH_APPLE_REDIRECT_URI=http://localhost:${vars.port}/auth/oauth/apple/callback`;

  const twilioNeeded = vars.enableSmsMfa || vars.enableWhatsAppMfa;

  const smsBlock = vars.enableSmsMfa
    ? `MFA_SMS_ENABLED=true`
    : `MFA_SMS_ENABLED=false`;

  const whatsappBlock = vars.enableWhatsAppMfa
    ? `MFA_WHATSAPP_ENABLED=true`
    : `MFA_WHATSAPP_ENABLED=false`;

  const telegramBlock = vars.enableTelegramMfa
    ? `MFA_TELEGRAM_ENABLED=true
TELEGRAM_BOT_TOKEN=`
    : `MFA_TELEGRAM_ENABLED=false
# TELEGRAM_BOT_TOKEN=`;

  const twilioBlock = twilioNeeded
    ? `# SMS / WhatsApp Provider (Twilio)
SMS_PROVIDER=twilio
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=
TWILIO_WHATSAPP_NUMBER=`
    : `# SMS / WhatsApp Provider (Twilio) — disabled
# SMS_PROVIDER=twilio
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
# TWILIO_PHONE_NUMBER=
# TWILIO_WHATSAPP_NUMBER=`;

  return `# ZeroAuth Configuration — ${vars.projectName}
# Generated by: npx zeroauth init
# Generated at: ${new Date().toISOString()}
#
# IMPORTANT: Keep this file secret. Never commit it to version control.
# Add .env to your .gitignore file.

# ─────────────────────────────────────────────────────────────────────────────
# Database Configuration
# ─────────────────────────────────────────────────────────────────────────────
MONGO_URI=${mongoUri}
MONGO_POOL_SIZE=10

# ─────────────────────────────────────────────────────────────────────────────
# Session Configuration
# ─────────────────────────────────────────────────────────────────────────────
SESSION_TTL=3600
REFRESH_TOKEN_TTL=604800
MAX_CONCURRENT_DEVICES=5

# ─────────────────────────────────────────────────────────────────────────────
# Security Configuration — AUTO-GENERATED (do not share these values)
# ─────────────────────────────────────────────────────────────────────────────
TOKEN_SECRET_HEX=${vars.tokenSecretHex}
CSFLE_MASTER_KEY_HEX=${vars.csfleKeyHex}
CSFLE_KEY_ROTATION_DAYS=90
BCRYPT_ROUNDS=12

# ─────────────────────────────────────────────────────────────────────────────
# OAuth Provider Configuration
# ─────────────────────────────────────────────────────────────────────────────

# Google OAuth
${googleBlock}

# GitHub OAuth
${githubBlock}

# Facebook OAuth
${facebookBlock}

# Apple OAuth
${appleBlock}

# ─────────────────────────────────────────────────────────────────────────────
# MFA Configuration
# ─────────────────────────────────────────────────────────────────────────────
TOTP_WINDOW=1
OTP_EXPIRY_SECS=900
MAX_OTP_ATTEMPTS=5

# MFA Channel Enablement
MFA_EMAIL_ENABLED=${vars.enableEmailMfa}
${smsBlock}
${whatsappBlock}
${telegramBlock}

${twilioBlock}

# Email Configuration (Nodemailer)
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER=
MAIL_PASSWORD=
MAIL_FROM=noreply@${vars.projectName.toLowerCase().replace(/\s+/g, "")}.dev

# ─────────────────────────────────────────────────────────────────────────────
# Rate Limiting Configuration
# ─────────────────────────────────────────────────────────────────────────────
RATE_LIMITING_ENABLED=true
RATE_LIMIT_PER_IP=100
RATE_LIMIT_WINDOW_SECS=60

# Redis Configuration (for distributed rate limiting and session caching)
REDIS_URI=${redisUri}

# ─────────────────────────────────────────────────────────────────────────────
# Geofencing Configuration
# ─────────────────────────────────────────────────────────────────────────────
GEOFENCING_ENABLED=false
ALLOWED_COUNTRIES=US,AU,EU,BD,IN
ALLOWED_IP_RANGES=

# ─────────────────────────────────────────────────────────────────────────────
# Elasticsearch Configuration (for audit logs)
# ─────────────────────────────────────────────────────────────────────────────
ELASTICSEARCH_ENABLED=${vars.useDocker}
ELASTICSEARCH_HOST=localhost
ELASTICSEARCH_PORT=9200
ELASTICSEARCH_INDEX_PREFIX=zeroauth

# ─────────────────────────────────────────────────────────────────────────────
# Logging Configuration
# ─────────────────────────────────────────────────────────────────────────────
LOG_LEVEL=info
LOG_FORMAT=json

# ─────────────────────────────────────────────────────────────────────────────
# Application Configuration
# ─────────────────────────────────────────────────────────────────────────────
NODE_ENV=development
PORT=${vars.port}
API_BASE_URL=http://localhost:${vars.port}

# ─────────────────────────────────────────────────────────────────────────────
# WebAuthn Configuration
# ─────────────────────────────────────────────────────────────────────────────
WEBAUTHN_RP_ID=localhost
WEBAUTHN_RP_NAME=${vars.projectName}
WEBAUTHN_RP_ORIGINS=http://localhost:${vars.port}

# ─────────────────────────────────────────────────────────────────────────────
# SSF (Shared Signals Framework) Configuration
# ─────────────────────────────────────────────────────────────────────────────
SSF_ENABLED=true
SSF_WEBHOOK_ENDPOINT=/ssf/events
SSF_SIGNING_SECRET=${vars.ssfSigningSecret}

# ─────────────────────────────────────────────────────────────────────────────
# Admin Configuration
# ─────────────────────────────────────────────────────────────────────────────
ADMIN_EMAIL=admin@${vars.projectName.toLowerCase().replace(/\s+/g, "")}.dev
ADMIN_PASSWORD_HASH=
`;
}
