apiVersion: v1
kind: Service
metadata:
  name: {{ include "zerotrust.fullname" . }}-api
  labels:
    {{- include "zerotrust.labels" . | nindent 4 }}
    app: zerotrust-api
spec:
  type: ClusterIP
  selector:
    app: zerotrust-api
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
