{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zerotrust.fullname" . }}
  labels:
    {{- include "zerotrust.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "zerotrust.fullname" $ }}-{{ .service }}
                port:
                  number: {{ if eq .service "api" }}{{ $.Values.api.service.port }}{{ else }}{{ $.Values.ui.service.port }}{{ end }}
          {{- end }}
    {{- end }}
{{- end }}
