apiVersion: v1
kind: Service
metadata:
  name: {{ include "zerotrust.fullname" . }}-ui
  labels:
    {{- include "zerotrust.labels" . | nindent 4 }}
    app: zerotrust-ui
spec:
  type: ClusterIP
  selector:
    app: zerotrust-ui
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
